import { defineConfig } from "tinacms";

// Branche déployée en production sur Cloudflare Pages — à changer ici si vous
// basculez vers "main" (même logique que l'ancien public/admin/config.yml de Decap).
const branch =
  process.env.GITHUB_BRANCH ||
  process.env.HEAD ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  "claude/installed-skills-overview-j4il8o";

export default defineConfig({
  branch,
  clientId: process.env.TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "images/uploads",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "spectacles",
        label: "Spectacles",
        path: "content",
        format: "json",
        match: { include: "spectacles" },
        ui: { global: true, router: () => "/spectacles" },
        fields: [
          {
            type: "object",
            name: "spectacles",
            label: "Spectacles",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.title || "Spectacle" }) },
            fields: [
              { type: "string", name: "id", label: "Identifiant (unique, sans espace)" },
              { type: "image", name: "image", label: "Photo (optionnel — sinon l'affiche générée s'affiche)" },
              { type: "string", name: "num", label: "Numéro" },
              { type: "string", name: "title", label: "Titre" },
              { type: "string", name: "tag", label: "Catégorie" },
              { type: "string", name: "date", label: "Date" },
              { type: "string", name: "duration", label: "Durée" },
              { type: "string", name: "ages", label: "Âge conseillé" },
              { type: "string", name: "color", label: "Couleur fond", ui: { component: "color" } },
              { type: "string", name: "textColor", label: "Couleur texte", ui: { component: "color" } },
              { type: "string", name: "desc", label: "Description", ui: { component: "textarea" } },
              { type: "string", name: "auteur", label: "Auteur" },
              { type: "string", name: "mes", label: "Mise en scène" },
              { type: "string", name: "with", label: "Avec (interprètes)" },
            ],
          },
        ],
      },
      {
        name: "agenda",
        label: "Agenda",
        path: "content",
        format: "json",
        match: { include: "agenda" },
        ui: { global: true, router: () => "/agenda" },
        fields: [
          {
            type: "object",
            name: "agenda",
            label: "Dates",
            list: true,
            ui: { itemProps: (item) => ({ label: `${item?.title || "Date"} — ${item?.day}/${item?.month}/${item?.year}` }) },
            fields: [
              { type: "image", name: "image", label: "Photo (optionnel — sinon la carte générée s'affiche)" },
              { type: "string", name: "day", label: "Jour" },
              { type: "string", name: "month", label: "Mois (3 lettres)" },
              { type: "string", name: "year", label: "Année" },
              { type: "string", name: "title", label: "Titre" },
              { type: "string", name: "venue", label: "Lieu" },
              { type: "string", name: "time", label: "Horaire / détail" },
              { type: "string", name: "price", label: "Prix" },
              { type: "string", name: "status", label: "Statut", options: ["free", "available"] },
              { type: "string", name: "type", label: "Type", options: ["résidence", "événement", "spectacle", "atelier"] },
              { type: "string", name: "cardColor", label: "Couleur carte", ui: { component: "color" } },
              { type: "string", name: "cardTextColor", label: "Couleur texte carte", ui: { component: "color" } },
              { type: "string", name: "spectacle", label: "Spectacle lié (identifiant, optionnel)", required: false },
            ],
          },
        ],
      },
      {
        name: "ateliers",
        label: "Ateliers",
        path: "content",
        format: "json",
        match: { include: "ateliers" },
        ui: { global: true, router: () => "/ateliers" },
        fields: [
          {
            type: "object",
            name: "ateliers",
            label: "Ateliers",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.title || "Atelier" }) },
            fields: [
              { type: "image", name: "image", label: "Photo (optionnel — sinon la carte de couleur s'affiche)" },
              { type: "string", name: "num", label: "Numéro" },
              { type: "string", name: "title", label: "Titre" },
              { type: "string", name: "who", label: "Public" },
              { type: "string", name: "when", label: "Horaires" },
              { type: "string", name: "where", label: "Lieu" },
              { type: "string", name: "price", label: "Prix" },
              { type: "string", name: "color", label: "Couleur fond", ui: { component: "color" } },
              { type: "string", name: "textColor", label: "Couleur texte", ui: { component: "color" } },
              { type: "string", name: "desc", label: "Description", ui: { component: "textarea" } },
              { type: "string", name: "audience", label: "Public cible", options: ["enfants", "ados", "adultes", "quartier"] },
              {
                type: "string",
                name: "recurrence",
                label: "Fréquence",
                options: [
                  { value: "ponctuel", label: "Ponctuel (pas de date récurrente dans l'agenda)" },
                  { value: "hebdomadaire", label: "Chaque semaine" },
                  { value: "mensuel", label: "Une fois par mois" },
                ],
              },
              {
                type: "string",
                name: "recurrenceDay",
                label: "Jour de la semaine",
                options: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
                required: false,
              },
              {
                type: "string",
                name: "recurrenceWeekOfMonth",
                label: "Quelle semaine du mois (fréquence mensuelle uniquement)",
                options: [
                  { value: "1", label: "1ère semaine" },
                  { value: "2", label: "2e semaine" },
                  { value: "3", label: "3e semaine" },
                  { value: "4", label: "4e semaine" },
                  { value: "dernier", label: "Dernière semaine du mois" },
                ],
                required: false,
              },
              { type: "datetime", name: "recurrenceStart", label: "Date de début", ui: { dateFormat: "DD/MM/YYYY" }, required: false },
              { type: "datetime", name: "recurrenceEnd", label: "Date de fin (optionnel — sinon généré jusqu'à 12 mois)", ui: { dateFormat: "DD/MM/YYYY" }, required: false },
              { type: "string", name: "recurrenceTime", label: "Horaire à afficher dans l'agenda (ex: 17h30–19h)", required: false },
            ],
          },
        ],
      },
      {
        name: "equipe",
        label: "Équipe",
        path: "content",
        format: "json",
        match: { include: "equipe" },
        ui: { global: true, router: () => "/equipe" },
        fields: [
          {
            type: "object",
            name: "equipe",
            label: "Membres",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.name || "Membre" }) },
            fields: [
              { type: "image", name: "image", label: "Photo (optionnel — sinon le portrait généré s'affiche)" },
              { type: "string", name: "name", label: "Nom" },
              { type: "string", name: "role", label: "Rôle" },
              {
                type: "string",
                name: "categorie",
                label: "Catégorie",
                options: [
                  { value: "permanente", label: "Équipe permanente" },
                  { value: "associee", label: "Artiste associé·e" },
                ],
              },
              { type: "string", name: "bio", label: "Bio", ui: { component: "textarea" } },
              { type: "string", name: "quote", label: "Citation (optionnel)", required: false },
            ],
          },
        ],
      },
      {
        name: "partenaires",
        label: "Partenaires",
        path: "content",
        format: "json",
        match: { include: "partenaires" },
        ui: { global: true, router: () => "/partenaires" },
        fields: [
          {
            type: "object",
            name: "partenaires",
            label: "Partenaires",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.name || "Partenaire" }) },
            fields: [
              { type: "image", name: "image", label: "Logo (optionnel — sinon les initiales s'affichent)" },
              { type: "string", name: "name", label: "Nom" },
              {
                type: "string",
                name: "type",
                label: "Type",
                options: [
                  "Soutien institutionnel",
                  "Partenaires artistiques",
                  "Action culturelle & territoire",
                  "Éducation",
                ],
              },
              { type: "string", name: "url", label: "Site web (optionnel)", required: false },
            ],
          },
        ],
      },
      {
        name: "home",
        label: "Page d'accueil",
        path: "content",
        format: "json",
        match: { include: "home" },
        ui: { global: true, router: () => "/" },
        fields: [
          {
            type: "object",
            name: "home",
            label: "Accueil",
            fields: [
              { type: "string", name: "heroEyebrow", label: "Bandeau saison" },
              { type: "string", name: "heroLine1", label: "Titre hero — ligne 1" },
              { type: "string", name: "heroLine2", label: "Titre hero — ligne 2" },
              { type: "string", name: "heroIntro", label: "Intro hero", ui: { component: "textarea" } },
              { type: "string", name: "heroTagline", label: "Accroche fondation" },
              {
                type: "object",
                name: "histoire",
                label: "Histoire d'un projet",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.label || "Section" }) },
                fields: [
                  { type: "string", name: "label", label: "Titre de la section" },
                  { type: "string", name: "teaser", label: "Résumé (accordéon fermé)", ui: { component: "textarea" } },
                  { type: "string", name: "paragraphs", label: "Paragraphes", list: true, ui: { component: "textarea" } },
                ],
              },
              { type: "string", name: "aboutTag", label: "À propos — mention" },
              { type: "string", name: "aboutTitle", label: "À propos — titre" },
              { type: "string", name: "aboutParagraphs", label: "À propos — paragraphes", list: true, ui: { component: "textarea" } },
              { type: "string", name: "publicsIntro", label: "Publics — texte d'intro", ui: { component: "textarea" } },
            ],
          },
        ],
      },
      {
        name: "contact",
        label: "Page Contact",
        path: "content",
        format: "json",
        match: { include: "contact" },
        ui: { global: true, router: () => "/contact" },
        fields: [
          {
            type: "object",
            name: "contact",
            label: "Contact",
            fields: [
              { type: "string", name: "meta", label: "Texte d'intro", ui: { component: "textarea" } },
              { type: "string", name: "addressName", label: "Nom (adresse)" },
              { type: "string", name: "addressLine1", label: "Adresse — ligne 1" },
              { type: "string", name: "addressLine2", label: "Adresse — ligne 2" },
              { type: "string", name: "email", label: "Email" },
              { type: "string", name: "website", label: "Site web" },
              { type: "string", name: "phone1", label: "Téléphone 1" },
              { type: "string", name: "phone2", label: "Téléphone 2" },
              { type: "string", name: "hours", label: "Horaires" },
              { type: "string", name: "access", label: "Accès (une ligne par moyen de transport)", list: true },
            ],
          },
        ],
      },
      {
        name: "mentionsLegales",
        label: "Mentions légales",
        path: "content",
        format: "json",
        match: { include: "mentionsLegales" },
        ui: { global: true, router: () => "/mentions-legales" },
        fields: [
          {
            type: "object",
            name: "mentionsLegales",
            label: "Mentions légales",
            fields: [
              { type: "string", name: "associationName", label: "Nom de l'association" },
              { type: "string", name: "siege", label: "Siège social" },
              { type: "string", name: "siret", label: "SIRET" },
              { type: "string", name: "representante", label: "Représentante légale" },
              { type: "string", name: "contactEmail", label: "Email de contact" },
              { type: "string", name: "hebergeurNom", label: "Hébergeur — nom" },
              { type: "string", name: "hebergeurAdresse", label: "Hébergeur — adresse" },
              { type: "string", name: "hebergeurUrl", label: "Hébergeur — site web" },
            ],
          },
        ],
      },
      {
        name: "presse",
        label: "Page Presse",
        path: "content",
        format: "json",
        match: { include: "presse" },
        ui: { global: true, router: () => "/presse" },
        fields: [
          {
            type: "object",
            name: "presse",
            label: "Presse",
            fields: [
              { type: "string", name: "intro", label: "Texte de présentation", ui: { component: "textarea" } },
              { type: "string", name: "contactEmail", label: "Email de contact presse" },
            ],
          },
        ],
      },
      {
        name: "footer",
        label: "Pied de page",
        path: "content",
        format: "json",
        match: { include: "footer" },
        ui: { global: true, router: () => "/" },
        fields: [
          {
            type: "object",
            name: "footer",
            label: "Footer",
            fields: [
              { type: "string", name: "tagline", label: "Texte de présentation", ui: { component: "textarea" } },
            ],
          },
        ],
      },
      {
        name: "newsletter",
        label: "Bloc newsletter",
        path: "content",
        format: "json",
        match: { include: "newsletter" },
        ui: { global: true, router: () => "/" },
        fields: [
          {
            type: "object",
            name: "newsletter",
            label: "Newsletter",
            fields: [
              { type: "string", name: "titleLine1", label: "Titre — ligne 1" },
              { type: "string", name: "titleLine2", label: "Titre — ligne 2" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
            ],
          },
        ],
      },
    ],
  },
});
